### ISSUE TITLE
autocommit lol

### ISSUE THREAD

**Issue by generationzcode** [RohanTrix/Competitive-Practice#3]
autocommit == keep the github stats BIG

**Comment by generationzcode** [comment]
smart tho. why did i open issue here tho.

**Comment by generationzcode** [comment]
mistake

**Comment by RohanTrix** [comment]
There is a autocommit manual too btw. :)

**Comment by generationzcode** [comment]
is that why ur github stats are so large lol? nice implementation but why now just make a random number and keep committing every second or less?

**Comment by generationzcode** [comment]
anyways ima use it myself. Also time.time() returns in seconds so waiting 60 seconds to commit once more seems odd. Is it to let the commit happen? to wait for it to complete?

**Comment by generationzcode** [comment]
actually no... I rarely use local environments and github stats dont matter lol. replit.com stats do. Got to get those cycles!

**Comment by RohanTrix** [comment]
It's not really for my GitHub stats, It was just to ease the adding and committing process. I am lazy so... :)

**Comment by generationzcode** [comment]
I would use it purely for the stats. However I use replit a lot more than
github, so they don't matter much.
